---
when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: [ manual, tag]

steps:
  - name: deploy-staging
    image: debian:latest
    environment:
      SSH_KEY:
        from_secret: ssh-key-staging
      REMOTE_HOST:
        from_secret: remote-host-staging
    when:
      event: push
      branch: ${CI_REPO_DEFAULT_BRANCH}
    commands:
      - apt-get update
      - apt-get install -y openssh-client rsync
      - mkdir -p $HOME/.ssh
      - ssh-keyscan -t rsa $REMOTE_HOST >> $HOME/.ssh/known_hosts
      - echo "$SSH_KEY" > "$HOME/.ssh/id_rsa"
      - chmod 0600 $HOME/.ssh/id_rsa
      - rsync -a --exclude '.git' --delete . $REMOTE_HOST:/var/swagger/libre-graph-api
  - name: deploy-production
    image: debian:latest
    environment:
      SSH_KEY:
        from_secret: ssh-key-production
      REMOTE_HOST:
        from_secret: remote-host-production
    when:
      event: tag
    commands:
      - apt-get update
      - apt-get install -y openssh-client rsync
      - mkdir -p $HOME/.ssh
      - ssh-keyscan -vvv -t rsa $REMOTE_HOST >> $HOME/.ssh/known_hosts
      - echo "$SSH_KEY" > "$HOME/.ssh/id_rsa"
      - chmod 0600 $HOME/.ssh/id_rsa
      - rsync -a --exclude '.git' --delete . woodpeckersyncer@$REMOTE_HOST:/var/swagger/libre-graph-api
